
import { BotConfig } from '../types';

export const generatePythonCode = (config: BotConfig): string => {
  const welcomeText = config.welcomeMessage.replace(/"/g, '\\"');
  const triggersJson = JSON.stringify(config.triggers || []);
  const buttonsJson = JSON.stringify(config.buttons || []);
  const antiSpamEnabled = config.antiSpam?.enabled || false;
  const rateLimit = config.antiSpam?.rateLimit || 10;
  
  return `#!/usr/bin/env python3
"""
BotEngine Pro - Autonomous Bot Instance
Generated by: BotEngine Systems
"""
import asyncio
import logging
import sys
import json
import aiosqlite
from datetime import datetime, timedelta
from aiogram import Bot, Dispatcher, Router, types, F
from aiogram.enums import ParseMode
from aiogram.filters import CommandStart, Command
from aiogram.types import Message, ReplyKeyboardMarkup, KeyboardButton
from aiogram.exceptions import TelegramForbiddenError, TelegramRetryAfter

# --- CORE SETTINGS ---
TOKEN = "${config.token}"
ADMIN_ID = ${config.adminChatId || 0}
DB_PATH = "bot_data.db"
TRIGGERS = ${triggersJson}
BUTTONS = ${buttonsJson}
ANTISPAM_ENABLED = ${antiSpamEnabled}
RATE_LIMIT = ${rateLimit}

# Internal cache for rate limiting
_flood_cache = {}

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.FileHandler("bot.log"),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger("Core")

bot = Bot(token=TOKEN, parse_mode=ParseMode.HTML)
dp = Dispatcher()
router = Router()

def get_main_keyboard():
    if not BUTTONS:
        return None
    keyboard_rows = []
    current_row = []
    for i, btn in enumerate(BUTTONS):
        current_row.append(KeyboardButton(text=btn['text']))
        if (i + 1) % 2 == 0:
            keyboard_rows.append(current_row)
            current_row = []
    if current_row:
        keyboard_rows.append(current_row)
    return ReplyKeyboardMarkup(keyboard=keyboard_rows, resize_keyboard=True)

async def db_init():
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute("""
            CREATE TABLE IF NOT EXISTS users (
                user_id INTEGER PRIMARY KEY,
                username TEXT,
                full_name TEXT,
                registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        await db.commit()

async def track_user(user: types.User):
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute(
            "INSERT OR IGNORE INTO users (user_id, username, full_name) VALUES (?, ?, ?)",
            (user.id, user.username, user.full_name)
        )
        await db.commit()

async def get_all_user_ids():
    async with aiosqlite.connect(DB_PATH) as db:
        async with db.execute("SELECT user_id FROM users") as cursor:
            return [row[0] for row in await cursor.fetchall()]

def is_flooding(user_id: int) -> bool:
    if not ANTISPAM_ENABLED: return False
    now = datetime.now()
    if user_id not in _flood_cache:
        _flood_cache[user_id] = []
    
    # Clean old records
    _flood_cache[user_id] = [t for t in _flood_cache[user_id] if t > now - timedelta(minutes=1)]
    
    if len(_flood_cache[user_id]) >= RATE_LIMIT:
        return True
    
    _flood_cache[user_id].append(now)
    return False

@router.message(CommandStart())
async def handle_start(message: Message):
    await track_user(message.from_user)
    kb = get_main_keyboard()
    await message.answer("${welcomeText}", reply_markup=kb)
    
    if ADMIN_ID and message.from_user.id != ADMIN_ID:
        try:
            await bot.send_message(ADMIN_ID, f"Notification: New user registration\\nID: {message.from_user.id}\\nName: {message.from_user.full_name}")
        except: pass

@router.message(Command("broadcast"))
async def handle_broadcast(message: Message):
    if not ADMIN_ID or message.from_user.id != ADMIN_ID: return
    
    content = message.text.replace("/broadcast", "").strip()
    if not content:
        return await message.answer("Usage: /broadcast <message_text>")
    
    uids = await get_all_user_ids()
    status = await message.answer(f"Status: Broadcasting to {len(uids)} nodes...")
    
    success = 0
    for uid in uids:
        try:
            await bot.send_message(uid, content)
            success += 1
            await asyncio.sleep(0.05) # Prevent Telegram flood limits
        except TelegramForbiddenError: continue
        except TelegramRetryAfter as e:
            await asyncio.sleep(e.retry_after)
            await bot.send_message(uid, content)
            success += 1
        except Exception as e:
            logger.error(f"Failed to send to {uid}: {e}")
            
    await status.edit_text(f"Broadcast finalized. Delivered: {success}/{len(uids)}")

@router.message()
async def main_handler(message: Message):
    if is_flooding(message.from_user.id): return
    await track_user(message.from_user)
    
    text = (message.text or "").lower()
    
    # 1. Menu Buttons
    for btn in BUTTONS:
        if btn['text'].lower() == text:
            return await message.answer(btn['response'])
            
    # 2. Keywords
    for trigger in TRIGGERS:
        if trigger['keyword'].lower() in text:
            return await message.answer(trigger['response'])

    # 3. Support logic (Admin relay)
    if ADMIN_ID and message.from_user.id != ADMIN_ID:
        forward_text = f"SUPPORT REQUEST\\nFrom ID: {message.from_user.id}\\nUser: {message.from_user.full_name}\\n\\n{message.text}"
        await bot.send_message(ADMIN_ID, forward_text)

    # 4. Operator response logic
    if ADMIN_ID and message.from_user.id == ADMIN_ID and message.reply_to_message:
        try:
            orig_msg = message.reply_to_message.text or ""
            if "From ID: " in orig_msg:
                target_id = int(orig_msg.split("From ID: ")[1].split("\\n")[0].strip())
                await bot.send_message(target_id, message.text)
                await message.reply("Response delivered.")
        except Exception as e:
            await message.reply(f"Delivery failed: {e}")

async def main():
    await db_init()
    dp.include_router(router)
    logger.info("Bot execution started")
    await dp.start_polling(bot)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except (KeyboardInterrupt, SystemExit):
        logger.info("Process terminated")
`;
};
